name: cazypipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - biopython=1.83
  - requests=2.32.0
  - beautifulsoup4=4.12.3
  - lxml=4.9.3
  - pip=23.3.1
  - pip:
    - setuptools>=65.0.0