---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "star_align"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::star=2.7.10a
