---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "star_align"
description: Align reads to a reference genome using STAR. #TODO Difference from this version and nf-core?
keywords:
  - align
  - fasta
  - genome
  - reference
tools:
  - "star":
      description: "STAR is a software package for mapping DNA sequences against 
                    a large reference genome, such as the human genome."
      homepage: "https://github.com/alexdobin/STAR"
      documentation: "https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf"
      doi: "10.1093/bioinformatics/bts635"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - reads:
      type: directory
      description: Path to reads

  - index:
      type: directory
      description: |
        STAR genome index,     
        `star_index = "/opt/projects/0001_Intomics/RNASeq_pipeline/rnaseq_pipeline/Refs/Homo_sapiens.GRCh38.103/RSEMSTAR"`


output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information

  - bam:
      type: file
      description: 
        Output BAM file containing read alignments
      pattern: "*.Aligned.toTranscriptome.out.bam"

  - log_final:
      type: file
      description: STAR final log file
      pattern: "*Log.final.out"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  # TODO should the last output be mentioned?
  # - other:
  #   type: file 
  #   pattern: "*"

authors:
  - "@zs"
maintainers:
  - "@zs"
