name: "fastq_align_star"
description: Build a reference, if necessary and align reads to a reference genome using STAR.
keywords:
  - index
  - align
  - fasta
  - genome
  - reference
tools:
  - "star":
      description: "STAR is a software package for mapping DNA sequences against 
                    a large reference genome, such as the human genome."
      homepage: "https://github.com/alexdobin/STAR"
      documentation: "https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf"
      doi: "10.1093/bioinformatics/bts635"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - ch_reads:
      type: directory
      description: Path to reads

  - ch_index:
      type: directory
      description: |
        Pre-built STAR genome index

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information

  - bam:
      type: file
      description: 
        Output BAM file containing read alignments
      pattern: "*.Aligned.toTranscriptome.out.bam"

  - log_final:
      type: file
      description: STAR final log file
      pattern: "*Log.final.out"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@fal"
